do

function run(msg, matches)
  return "ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ZAC™ "
end
return {
  description = "سازنده", 
  usage = "/credits",
  patterns = {
    "^/zac$",
    "^!zac$",
    "^/Zac$",
    "^!Zak$",
  },
  run = run
}
end
